name: MultiCooker Gourmet
favicon: null
layout_spectrum: 0.5106160982977599
typography_spectrum: 0.17042
title: MultiCooker Gourmet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5
  lightness: 0.03644394222646952
  saturation: 0.5
  rhythmicContrast: 0.047693068627268076
purpose: []
